"""
compliance.py — Indian legal and regulatory compliance for Arbiter.

Covers: IT Act 2000, DPDP Act 2023, Bar Council Rules,
Consumer Protection Act 2019, IT Intermediary Rules 2021.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

ARBITER_DISCLAIMER = """
IMPORTANT LEGAL NOTICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This document has been generated by Arbiter, an AI-powered legal document
drafting service. It is provided for informational and self-help purposes ONLY.

THIS IS NOT LEGAL ADVICE.

Arbiter is not a law firm. No attorney-client relationship is created by using
this service. The document generated here has not been reviewed by a licensed
advocate or solicitor.

CONSULT A QUALIFIED LAWYER before filing in any court or sending to any authority
if the dispute amount exceeds ₹20 lakhs or criminal charges may be involved.

Arbiter and its operators accept no liability for outcomes arising from use of
this document.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Arbiter AI | arbiter.in | support@arbiter.in
"""

DATA_RETENTION_DAYS = {
    "cases": 1825,
    "documents": 1825,
    "conversation_history": 365,
    "payment_records": 2190,
    "audit_logs": 2190,
}

GRIEVANCE_OFFICER = {
    "name": "Preet Singh",
    "designation": "Grievance Officer",
    "email": "grievance@arbiter.in",
    "response_time_hours": 24,
    "resolution_time_days": 15,
}

PRIVACY_POLICY_URL = "https://arbiter.in/privacy"
TERMS_OF_SERVICE_URL = "https://arbiter.in/terms"
REFUND_POLICY_URL = "https://arbiter.in/refund"


def get_compliance_metadata() -> dict:
    """Returns compliance metadata for the /health/compliance endpoint."""
    return {
        "it_act_2000": {
            "status": "compliant",
            "security_practices": "Firestore security rules + Firebase Auth + HTTPS",
            "data_localisation": "asia-south1 (India)",
        },
        "dpdp_act_2023": {
            "status": "compliant",
            "consent_mechanism": "Firebase Auth sign-up with ToS acceptance",
            "data_minimisation": "Only intake data required for document generation is collected",
            "right_to_erasure": "Supported via DELETE /api/users/{id}/data endpoint",
            "data_localisation": "asia-south1 (India) ✓",
        },
        "bar_council_rules": {
            "status": "compliant",
            "disclaimer": "Mandatory disclaimer on every generated document",
            "no_legal_advice": "Service explicitly provides documents, not legal advice",
            "lawyer_referral": "Complex matters referred to verified pro-bono lawyers",
        },
        "consumer_protection_act_2019": {
            "status": "compliant",
            "pricing_transparency": "Price shown before purchase (₹299/document, ₹799/month)",
            "grievance_officer": GRIEVANCE_OFFICER["email"],
        },
        "it_intermediary_rules_2021": {
            "status": "compliant",
            "grievance_officer": GRIEVANCE_OFFICER,
            "content_policy": "Legal documents only; refusal of illegal content",
        },
        "generated_at": datetime.utcnow().isoformat(),
    }


def get_data_processing_notice() -> str:
    """Returns the data processing notice shown to users at sign-up."""
    return (
        "By creating an account, you consent to Arbiter collecting and processing "
        "the personal information you provide solely for generating legal documents. "
        f"Your data is stored securely in India and retained for up to 5 years. "
        f"You may request deletion at any time by writing to {GRIEVANCE_OFFICER['email']}."
    )


def validate_document_for_compliance(content: str, document_type: str) -> list[str]:
    """Check a generated document for compliance issues. Returns list of warnings."""
    warnings = []

    if "NOT LEGAL ADVICE" not in content.upper() and "DISCLAIMER" not in content.upper():
        warnings.append("Document missing mandatory legal disclaimer.")

    if "attorney-client" in content.lower() and "does not create" not in content.lower():
        warnings.append("Document may incorrectly imply attorney-client relationship.")

    if document_type == "rti_application" and "Right to Information Act, 2005" not in content:
        warnings.append("RTI application must cite Right to Information Act, 2005.")

    if document_type == "consumer_complaint" and "Consumer Protection Act" not in content:
        warnings.append("Consumer complaint must cite Consumer Protection Act, 2019.")

    return warnings
