import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: 'Arbiter legal disclaimer.',
}

export default function DisclaimerPage() {
  return (
    <main className="bg-black min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-20">
        <a href="/" className="text-[#444] hover:text-white text-sm transition-colors mb-8 inline-block">
          ← Back to home
        </a>
        <h1 className="text-3xl font-bold text-white mb-2">Legal Disclaimer</h1>
        <p className="text-[#444] text-sm mb-12">Effective: May 2026</p>

        <div className="space-y-6 legal-text">
          <p><strong className="text-white">AI-Generated Content:</strong> All documents produced by Arbiter are generated by artificial intelligence (Google Gemini). While we strive for accuracy, AI-generated legal documents may contain errors, omissions, or outdated information.</p>
          <p><strong className="text-white">Not Legal Advice:</strong> Using Arbiter does not create an attorney-client relationship. Arbiter is a document drafting tool, not a law firm or legal adviser. No information on this platform should be construed as legal advice.</p>
          <p><strong className="text-white">Jurisdiction:</strong> Indian law varies by state, district, and case-specific facts. Documents generated by Arbiter are based on central Indian law and may not account for all local variations.</p>
          <p><strong className="text-white">Review Before Use:</strong> Always read and review any document generated by Arbiter before sending it to any party or filing it with any authority. Consider having a lawyer review it for high-stakes matters.</p>
          <p><strong className="text-white">Limitation of Liability:</strong> Arbiter and its creators shall not be liable for any damages, losses, or adverse outcomes resulting from the use of documents generated on this platform.</p>
        </div>
      </div>
    </main>
  )
}
